// Package blockly implements the JSON parser and execution engine for QuantFlow's
// Blockly-based strategy logic. It converts JSONB payloads from
// strategy_versions.logic_json into a traversable AST and drives execution.
//
// Task 2.5.1 — JSON Parser and Block Registry (26 block types).
// WBS: P2-Backend · 11/03/2026
// SRS: FR-DESIGN-01→10, FR-RUN-02, FR-RUN-05, FR-RUN-07
package blockly

import (
	"encoding/json"
	"fmt"
)

// ═══════════════════════════════════════════════════════════════════════════
//  Blockly 12.x JSON Serialization Structs
// ═══════════════════════════════════════════════════════════════════════════

// BlocklyWorkspace is the top-level struct that maps to the root of logic_json
// stored in strategy_versions.logic_json (Database Schema §4).
// It is generated by Blockly 12.x's serialization.workspaces.save() on the
// frontend and stored verbatim as JSONB in PostgreSQL.
type BlocklyWorkspace struct {
	Blocks WorkspaceBlocks `json:"blocks"`
}

// WorkspaceBlocks wraps the array of top-level blocks serialized by Blockly.
type WorkspaceBlocks struct {
	LanguageVersion int     `json:"languageVersion"`
	Blocks          []Block `json:"blocks"`
}

// Block represents a single node in the Blockly AST.
// It models both statement blocks (previousStatement/nextStatement chains)
// and value blocks (those with an output that feed into input slots).
type Block struct {
	// Type is the block's registered identifier (e.g., "event_on_candle",
	// "controls_if", "trade_smart_order"). Must exist in blockRegistry.
	Type string `json:"type"`

	// ID is the unique client-generated identifier assigned by Blockly.
	// Used for debugging and log correlation.
	ID string `json:"id"`

	// Fields holds scalar parameters configured directly on the block:
	// dropdown selections (string) and numeric field values (float64).
	// Examples: {"TRIGGER": "ON_CANDLE_CLOSE"}, {"LEVERAGE": 10}.
	// JSON numbers decode to float64 when unmarshaled into interface{}.
	Fields map[string]interface{} `json:"fields"`

	// Inputs holds connected child blocks — both value inputs (providing
	// a computed result) and statement inputs (inner block chains).
	// Examples: {"CONDITION": {...}, "DO": {...}, "QUANTITY": {...}}.
	Inputs map[string]BlockInput `json:"inputs"`

	// Next links to the following block in a statement chain.
	// Nil when this block is the last in its chain.
	Next *NextBlock `json:"next"`
}

// BlockInput represents one named input slot on a parent block.
// A slot can hold a live Block (user-connected) or a Shadow block (the Blockly
// default placeholder). Execution always uses Block; Shadow is parsed for
// completeness and may be used as a fallback in future extensions.
type BlockInput struct {
	Block  *Block `json:"block"`
	Shadow *Block `json:"shadow"`
}

// NextBlock wraps the pointer to the next statement block in a chain.
// Wrapping avoids a direct pointer-in-struct JSON cycle between Block.Next
// and Block itself.
type NextBlock struct {
	Block *Block `json:"block"`
}

// ═══════════════════════════════════════════════════════════════════════════
//  Block Group Classification
// ═══════════════════════════════════════════════════════════════════════════

// BlockGroup identifies the functional category of a block as defined in
// blockly.md §2 (Toolbox structure). Used for logging and dispatch.
type BlockGroup string

const (
	// BlockGroupEvent — Sự kiện (Event Trigger): 1 block
	BlockGroupEvent BlockGroup = "event"
	// BlockGroupLogic — Logic & Điều khiển (Logic & Control): 8 blocks
	BlockGroupLogic BlockGroup = "logic"
	// BlockGroupMath — Toán học (Math): 4 blocks
	BlockGroupMath BlockGroup = "math"
	// BlockGroupVariable — Biến (Session & Lifecycle Variables): 4 blocks
	BlockGroupVariable BlockGroup = "variable"
	// BlockGroupIndicator — Chỉ báo Kỹ thuật (Technical Indicators): 2 blocks
	BlockGroupIndicator BlockGroup = "indicator"
	// BlockGroupData — Dữ liệu Thị trường & Tài khoản (Market/Account Data): 4 blocks
	BlockGroupData BlockGroup = "data"
	// BlockGroupTrade — Đặt lệnh & Quản lý lệnh (Order Placement & Management): 3 blocks
	BlockGroupTrade BlockGroup = "trade"
)

// ═══════════════════════════════════════════════════════════════════════════
//  Block Registry — 26 Custom Block Types
// ═══════════════════════════════════════════════════════════════════════════

// BlockMeta holds compile-time metadata for a registered block type.
// UnitCost is the number of units consumed per execution of this block,
// as specified in blockly.md §1.4 (Unit Cost Table).
type BlockMeta struct {
	Type     string
	Group    BlockGroup
	UnitCost int
}

// blockRegistry is the authoritative compile-time registry of all 26 custom
// block types defined in blockly.md. Any block type present in a strategy's
// logic_json but absent from this map is rejected as invalid during parsing.
//
// Unit cost values are sourced from blockly.md §1.4.
var blockRegistry = map[string]BlockMeta{

	// ── Group 1: Event Trigger (1 block) ──────────────────────────────────
	// Unit cost 0 — session start point, no computation charge (blockly.md §1.4)
	"event_on_candle": {
		Type: "event_on_candle", Group: BlockGroupEvent, UnitCost: 0,
	},

	// ── Group 2: Logic & Control (8 blocks) ───────────────────────────────
	// Unit cost 1 per evaluation; loops charge 1 per iteration (blockly.md §1.4)
	"controls_if": {
		Type: "controls_if", Group: BlockGroupLogic, UnitCost: 1,
	},
	"controls_if_else": {
		Type: "controls_if_else", Group: BlockGroupLogic, UnitCost: 1,
	},
	"logic_compare": {
		Type: "logic_compare", Group: BlockGroupLogic, UnitCost: 1,
	},
	"logic_operation": {
		Type: "logic_operation", Group: BlockGroupLogic, UnitCost: 1,
	},
	"logic_negate": {
		Type: "logic_negate", Group: BlockGroupLogic, UnitCost: 1,
	},
	"logic_boolean": {
		Type: "logic_boolean", Group: BlockGroupLogic, UnitCost: 1,
	},
	// controls_repeat and controls_while each charge 1 unit per loop iteration,
	// not once per block encounter. The executor handles this in block_logic.go
	// (Task 2.5.2) by calling UnitTracker.Consume(1) inside the loop body.
	"controls_repeat": {
		Type: "controls_repeat", Group: BlockGroupLogic, UnitCost: 1,
	},
	"controls_while": {
		Type: "controls_while", Group: BlockGroupLogic, UnitCost: 1,
	},

	// ── Group 3: Math (4 blocks) ───────────────────────────────────────────
	// Unit cost 1 — simple arithmetic in RAM (blockly.md §1.4)
	"math_number": {
		Type: "math_number", Group: BlockGroupMath, UnitCost: 1,
	},
	"math_arithmetic": {
		Type: "math_arithmetic", Group: BlockGroupMath, UnitCost: 1,
	},
	"math_round": {
		Type: "math_round", Group: BlockGroupMath, UnitCost: 1,
	},
	"math_random_int": {
		Type: "math_random_int", Group: BlockGroupMath, UnitCost: 1,
	},

	// ── Group 4: Variables — Session & Lifecycle (4 blocks) ───────────────
	// Unit cost 1 — RAM read/write (session) or DB JSONB read/write (lifecycle)
	"variables_session_set": {
		Type: "variables_session_set", Group: BlockGroupVariable, UnitCost: 1,
	},
	"variables_session_get": {
		Type: "variables_session_get", Group: BlockGroupVariable, UnitCost: 1,
	},
	"variables_lifecycle_set": {
		Type: "variables_lifecycle_set", Group: BlockGroupVariable, UnitCost: 1,
	},
	"variables_lifecycle_get": {
		Type: "variables_lifecycle_get", Group: BlockGroupVariable, UnitCost: 1,
	},

	// ── Group 5: Technical Indicators (2 blocks) ──────────────────────────
	// Unit cost 5 — requires candle data query + iterative mathematical computation
	"indicator_rsi": {
		Type: "indicator_rsi", Group: BlockGroupIndicator, UnitCost: 5,
	},
	"indicator_ema": {
		Type: "indicator_ema", Group: BlockGroupIndicator, UnitCost: 5,
	},

	// ── Group 6: Trading — Market & Account Data (4 blocks) ───────────────
	// Unit cost 3 — requires live exchange API call to retrieve data
	"data_market_price": {
		Type: "data_market_price", Group: BlockGroupData, UnitCost: 3,
	},
	"data_position_info": {
		Type: "data_position_info", Group: BlockGroupData, UnitCost: 3,
	},
	"data_open_orders_count": {
		Type: "data_open_orders_count", Group: BlockGroupData, UnitCost: 3,
	},
	"data_balance": {
		Type: "data_balance", Group: BlockGroupData, UnitCost: 3,
	},

	// ── Group 6: Trading — Order Placement & Management (3 blocks) ────────
	// Unit cost 10 — direct impact on live account, involves multiple API calls
	// (leverage check → margin type check → order placement)
	"trade_smart_order": {
		Type: "trade_smart_order", Group: BlockGroupTrade, UnitCost: 10,
	},
	"trade_close_position": {
		Type: "trade_close_position", Group: BlockGroupTrade, UnitCost: 10,
	},
	"trade_cancel_all_orders": {
		Type: "trade_cancel_all_orders", Group: BlockGroupTrade, UnitCost: 10,
	},
}

// ═══════════════════════════════════════════════════════════════════════════
//  Parse & Validate
// ═══════════════════════════════════════════════════════════════════════════

// ParseLogicJSON unmarshals raw JSONB bytes from strategy_versions.logic_json
// (stored as []byte in domain.StrategyVersion.LogicJSON) into a traversable
// Block AST.
//
// It returns the root *Block — always an event_on_candle block — which serves
// as the entry point for the execution engine (ExecuteChain / ExecuteBlock).
// Returns a descriptive error if the JSON is malformed or the root block is
// not a valid event_on_candle.
func ParseLogicJSON(raw []byte) (*Block, error) {
	var workspace BlocklyWorkspace
	if err := json.Unmarshal(raw, &workspace); err != nil {
		return nil, fmt.Errorf("blockly: failed to unmarshal logic_json: %w", err)
	}

	if len(workspace.Blocks.Blocks) == 0 {
		return nil, ErrEmptyWorkspace
	}

	// QuantFlow strategies must have exactly one top-level block: event_on_candle.
	// Multi-root workspaces are not supported in v1.0.
	root := &workspace.Blocks.Blocks[0]
	if err := ValidateRootBlock(root); err != nil {
		return nil, err
	}

	return root, nil
}

// ValidateRootBlock ensures the given block is an event_on_candle block.
// Every valid QuantFlow strategy must begin with an event trigger block
// (SRS FR-RUN-02, blockly.md §3.1 — "required start block").
func ValidateRootBlock(root *Block) error {
	if root == nil {
		return ErrEmptyWorkspace
	}
	if root.Type != "event_on_candle" {
		return fmt.Errorf("%w: got %q", ErrInvalidRootBlock, root.Type)
	}
	return nil
}

// GetBlockMeta returns the registry metadata for the given block type string.
// Returns ErrUnknownBlockType if the type is not one of the 26 registered types.
// This is the authoritative check used by ExecuteBlock before dispatch.
func GetBlockMeta(blockType string) (BlockMeta, error) {
	meta, ok := blockRegistry[blockType]
	if !ok {
		return BlockMeta{}, fmt.Errorf("%w: %q", ErrUnknownBlockType, blockType)
	}
	return meta, nil
}

// ═══════════════════════════════════════════════════════════════════════════
//  Safe Field & Input Accessors
// ═══════════════════════════════════════════════════════════════════════════

// GetInputBlock safely retrieves the connected Block from a named input slot.
//
// Blockly 12 input slots can hold two kinds of child block:
//   - Block  — a user-connected block (explicitly dragged into the slot).
//   - Shadow — a default placeholder block (set in the toolbox config).
//
// When the user edits a shadow block's fields (e.g., typing a number into
// the default math_number placeholder), Blockly serializes it under the
// "shadow" key — NOT under "block". If the user drags a separate block
// into the slot, Blockly stores that under "block" (the shadow is hidden).
//
// Execution semantics: use Block if present (user explicitly connected
// something), otherwise fall back to Shadow (the default placeholder value).
// Returns nil only when the slot is truly empty (no block or shadow).
func GetInputBlock(b *Block, inputName string) *Block {
	if b == nil || b.Inputs == nil {
		return nil
	}
	slot, ok := b.Inputs[inputName]
	if !ok {
		return nil
	}
	// Prefer user-connected block; fall back to shadow (default placeholder).
	if slot.Block != nil {
		return slot.Block
	}
	return slot.Shadow
}

// GetBodyBlock resolves the strategy body (first child statement) from the
// root event_on_candle block.
//
// The event_on_candle block definition uses `nextStatement` (not
// `input_statement "DO"`), so the strategy body is serialized under
// root.Next.Block in Blockly 12's JSON format — NOT under root.Inputs["DO"].
//
// This helper checks both locations for forward compatibility: Inputs["DO"]
// first (the original design assumption), then Next.Block (the actual format).
func GetBodyBlock(root *Block) *Block {
	if root == nil {
		return nil
	}
	// Preferred: check Inputs["DO"] (input_statement "DO" wiring)
	if body := GetInputBlock(root, "DO"); body != nil {
		return body
	}
	// Fallback: check Next (nextStatement wiring — actual Blockly 12 format)
	if root.Next != nil {
		return root.Next.Block
	}
	return nil
}

// GetFieldString safely retrieves a block field value as a string.
// Used for dropdown fields (e.g., TRIGGER, TIMEFRAME, OP, SIDE, ORDER_TYPE,
// PRICE_TYPE, FIELD, MARGIN_TYPE) which Blockly serializes as JSON strings.
// Returns an empty string if the field is absent or not a string type.
func GetFieldString(b *Block, fieldName string) string {
	if b == nil || b.Fields == nil {
		return ""
	}
	v, ok := b.Fields[fieldName]
	if !ok {
		return ""
	}
	s, _ := v.(string)
	return s
}

// GetFieldFloat safely retrieves a block field value as float64.
// Used for numeric fields (e.g., NUM, LEVERAGE, DECIMALS, value) which Blockly
// serializes as JSON numbers. encoding/json decodes JSON numbers into interface{}
// as float64 by default, so this type assertion is safe for standard JSON input.
// Returns 0 if the field is absent or cannot be asserted to float64.
func GetFieldFloat(b *Block, fieldName string) float64 {
	if b == nil || b.Fields == nil {
		return 0
	}
	v, ok := b.Fields[fieldName]
	if !ok {
		return 0
	}
	f, _ := v.(float64)
	return f
}
